### ISSUE TITLE
have you seen @esri/arcgis-rest-request?

### ISSUE THREAD

**Issue by jgravois** [tannerjt/backuparcgis-service#1]
hey @tannerjt! :wave:

could be helpful for a lib like this

https://esri.github.io/arcgis-rest-js/guides/package-overview/

**Comment by tannerjt** [comment]
Hey @jgravois!  I really like the work being done with [arcgis-rest-js](https://github.com/Esri/arcgis-rest-js) and excited to see others using NodeJS with ArcGIS.

Right now I'm using the core [HTTPS](https://nodejs.org/dist/latest-v10.x/docs/api/https.html) module to pipe the readable stream chunks from the Feature Service (geojson) directly to a temporary file.  I'm also creating a unique hash for comparing any previously stored backups.  Here's the [logic for the hashing and promise response](https://github.com/tannerjt/backuparcgis-service/blob/master/lib/https-promise.js).

My thought process was that streaming the response directly to a file would reduce the memory footprint of backing up many or large feature services in a single script.  From my understanding, the [arcgis-rest-request](https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-request/src/request.ts) would return a promise with the entire response, which I believe would buffer everything into memory.  

Do you know if this would be the case?

**Comment by jgravois** [comment]
you're correct. i'd be happy to help you land a PR to expose (the fetch non-standard) `stream` if it'd be useful though. 

it would be _really_ straightforward.

relevant discussion: https://github.com/Esri/arcgis-rest-js/pull/374#issuecomment-434732939

**Comment by tannerjt** [comment]
Thanks!  I took a look and added a [comment](https://github.com/Esri/arcgis-rest-js/pull/374#issuecomment-462553066) the the thread in the arcgis-rest-js library.  Let me know what you think and I can dig deeper.

**Comment by jgravois** [comment]
thx man!

a PR would definitely be welcome. if not, I'll get around to it someday.

**Comment by tannerjt** [comment]
Absolutely.  I'll look at the best way to integrate and submit a PR.  I just wanted to make sure sure the logic looked sound.
